apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: kong/httpbin:0.1.0
        name: httpbin
        ports:
        - containerPort: 80
