apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-04-16T20:02:56Z"
    generation: 1
    labels:
      app: httpbin
    name: httpbin
    namespace: pucminas
    resourceVersion: "5916"
    uid: bc39019b-a61d-4dcd-8d68-2e700071b69a
  spec:
    progressDeadlineSeconds: 600
    replicas: 4
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: httpbin
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: httpbin
      spec:
        containers:
        - image: kong/httpbin:0.1.0
          imagePullPolicy: IfNotPresent
          name: httpbin
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 4
    conditions:
    - lastTransitionTime: "2024-04-16T20:03:23Z"
      lastUpdateTime: "2024-04-16T20:03:23Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-04-16T20:02:56Z"
      lastUpdateTime: "2024-04-16T20:03:26Z"
      message: ReplicaSet "httpbin-7bcb9d9df" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 4
    replicas: 4
    updatedReplicas: 4
kind: List
metadata:
  resourceVersion: ""
